# Profile information
name: Mishal Shah
title: Mishal Shah
description: "Mishal Shah"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mishal23.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: mishal.shah.7731
twitter: 1998Mishal
google-plus: u/0/101714954506157781527
github: mishal23
linkedin: in/mishal23/
analytics: UA-110715968-2

# Contact form
email: shahmishal1998@gmail.com

# Comments
discus-identifier: mishal23 # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]